### ISSUE TITLE
the installer does not recognise the EFI partition

### ISSUE THREAD

**Issue by maenpaa24** [wifislax-ng/instaladorHDD#1]
Hi!

I already have created and used an EFI partition on my ssd drive, which is formatted to FAT32 and labeled with boot and esp. However whenever I click on the wifislax installer it says that such EFI partition is required and that I should open gparted to create it.

It is an nvme ssd which is recognised in disk and dolphin can access to its files in other partitions.

I am using wifislax 64 bit 1.1

Thank you in advance.

**Comment by vk496** [comment]
Hello,

Maybe the problem is that you are using a MBR partition structure instead
of GPT...

Salu2

**Comment by maenpaa24** [comment]
No, I have a gpt partition structure for sure, I have really taken care of any detail. For example, I have double checked that the GPT's MBR partition is protectionist and not hybrid, which can be checked with gdisk. I have installed several operating systems in EFI mode. It is a MacBook.

Regards and thanks.

**Comment by maenpaa24** [comment]
I have got to the conclusion that the problem is that it is an nvme drive whose name usually differs from the sata drive's names. SATA's names are usually sda, sdb, sdc,... and nvme's names are usually nvme0n1, nvme0n2,... or things like that so, what must be done is adding such name to the instalador en HDD code at the following point:

if [ $EFI -eq 0 ]; then
	EFI_TMP=$(mktemp)
	
	# Scan for EFI partitions:
	for drive in sda sdb sdc sdd sde sdf sdg sdh sdi sdj sdk sdl sdm sdn sdo sdp mmcblk0 nvme0n1; do
	  if LANG=C fdisk -l /dev/$drive 2> /dev/null | grep -q "Disklabel type: gpt" ; then
		gdisk -l /dev/$drive 2> /dev/null | grep -w EF00 | while read efisp ; do
		  	if echo $drive | grep -q "mmc"; then
		  		echo /dev/${drive}p$(expr $(echo "$efisp" | cut -b 1-4)) >> $EFI_TMP
			else
				echo /dev/$drive$(expr $(echo "$efisp" | cut -b 1-4)) >> $EFI_TMP
			fi
		done
	  fi
	done
	
	if [ "$(cat $EFI_TMP)" = "" ]; then # No EFI partitions
		EFI_MESSAGE="-Una partición EFI (FAT32 de +100MB con flags \"boot\" y \"esp\")"
		EFI_ERROR=0
fi

**Comment by vk496** [comment]
Hello,

Thanks for the info. I forgot to mention that is possible to debug bash:

`bash -x /path/to/script.sh`

In the other side... Is nvme0n1 or nvme0?

Seems like *n1* is the partition, not the drive.

Salu2


El 12 dic. 2017 12:43 p. m., "maenpaa24" <notifications@github.com>
escribió:

I have got to the conclusion that the problem is that it is an nvme drive
whose name usually differs from the sata drive's names. SATA's names are
usually sda, sdb, sdc,... and nvme's names are usually nvme0n1, nvme0n2,...
or things like that so, what must be done is adding such name to the
instalador en HDD code at the following point:

if [ $EFI -eq 0 ]; then
EFI_TMP=$(mktemp)

# Scan for EFI partitions:
for drive in sda sdb sdc sdd sde sdf sdg sdh sdi sdj sdk sdl sdm sdn
sdo sdp mmcblk0 nvme0n1; do
  if LANG=C fdisk -l /dev/$drive 2> /dev/null | grep -q "Disklabel
type: gpt" ; then
	gdisk -l /dev/$drive 2> /dev/null | grep -w EF00 | while read efisp ; do
	  	if echo $drive | grep -q "mmc"; then
	  		echo /dev/${drive}p$(expr $(echo "$efisp" | cut -b 1-4)) >> $EFI_TMP
		else
			echo /dev/$drive$(expr $(echo "$efisp" | cut -b 1-4)) >> $EFI_TMP
		fi
	done
  fi
done

if [ "$(cat $EFI_TMP)" = "" ]; then # No EFI partitions
	EFI_MESSAGE="-Una partición EFI (FAT32 de +100MB con flags \"boot\" y \"esp\")"
	EFI_ERROR=0

fi

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/wifislax-ng/instaladorHDD/issues/1#issuecomment-351027564>,
or mute the thread

**Comment by maenpaa24** [comment]
You are welcome!

In my case the only nvme drive I have is called nvme0n1 whereas the partitions are named nvme0n1p1, nvmen1p2, and so on...

**Comment by vk496** [comment]
@maenpaa24 Maybe now should work.

Replace files from this repo intro LiveCD and try install again..

Should be a better way to do that staff instead of the 'Slackware way'...


Salu2

**Comment by maenpaa24** [comment]
Yes now it does!

thanks and regards

**Comment by vk496** [comment]
Many thanks for the great research!

Salu2
